#!/bin/sh /etc/rc.common
#
# Copyright 2022-2025 lava <byl0561@gmail.com>
#

START=99
USE_PROCD=1

NAME=eqosplus
LOCKDIR="/tmp/$NAME.lock"
CR=/etc/crontabs/root

start_instance() {
	procd_open_instance
	procd_set_param command /usr/bin/eqosplusctrl
	procd_set_param respawn
	procd_set_param stderr 1
	procd_close_instance
}

_eqosplus_stop() {
	kill $(busybox ps -w | grep 'eqosplusctrl' | grep -v 'grep' | awk '{print $1}') >/dev/null 2>&1
	sed -i '/eqosplus/d' $CR >/dev/null 2>&1
	eqosplus stop
}

_eqosplus_start() {
	if [ "$(uci -q get $NAME.@eqosplus[0].service_enable)" = "1" ]; then
		if [ x$(uci -q get turboacc.config.sw_flow) = 'x1' ] || [ x$(uci -q get turboacc.config.sfe_flow) = 'x1' ]; then
			uci -q set turboacc.config.sw_flow='0'
			uci -q set turboacc.config.sfe_flow='0'
			uci -q set turboacc.config.hw_flow='0'
			uci commit turboacc
			/etc/init.d/turboacc restart
		fi
		eqosplus start
		start_instance
		(crontab -l ; echo "00 1 * * * /etc/init.d/eqosplus start") | sort - | uniq - | crontab -
	fi
}

start_service(){
	mkdir $LOCKDIR 2>/dev/null || exit 0
	_eqosplus_stop
	_eqosplus_start
}

service_triggers() {
	procd_add_reload_trigger 'eqosplus'
}

stop_service(){
	_eqosplus_stop
	rmdir $LOCKDIR 2>/dev/null
}
